version: "3.8"

services:
  db:
    container_name: db
    image: postgres:latest
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - rubcamp
    env_file:
      - .env.docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rubcamp"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: yarn dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3344:3344
      - 6666:6666
      - 9229:9229
    networks:
      - rubcamp
    links:
      - db
    env_file:
      - .env
    platform: "linux/amd64"
    depends_on:
      db:
        condition: service_healthy

networks:
  rubcamp:
    driver: bridge
